"""
Django settings for volunteer_tracker_app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-ytu@ckohy(ieunx=cyqxwoljel_wr@%a60!d_b!b8!^v=ii9(b'

# SECURITY WARNING: don't run with debug turned on in production!
MODE = os.environ.get("MODE")

print(f"ENVS:")
print(f"MODE: {MODE}")

if MODE == "dev":
    DEBUG = True
else:
    DEBUG = False


SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'fallback-secret')
######DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'
# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS")
# if ALLOWED_HOSTS:
#     ALLOWED_HOSTS = ALLOWED_HOSTS.split(",")
# else:
#     ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS")
if CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS.split(",")
else:
    # fallback for local testing
    CSRF_TRUSTED_ORIGINS = ["https://localhost", "https://127.0.0.1", "https://mtbtest.casteel.pw"]

# Force the session cookie to be sent even when coming from an external link (like Gmail)
SESSION_COOKIE_SAMESITE = 'Lax' 

# If you are NOT using HTTPS (testing on a local IP like 10.0.10.140), 
# make sure these are False:
if MODE == "dev":
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'crispy_bulma',
    'django_q',
    # custom apps
    'hourTracker',

]
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bulma",)
CRISPY_TEMPLATE_PACK = "bulma"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'volunteer_tracker_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hourTracker.context_processor.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'volunteer_tracker_app.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'django'),
        'USER': os.environ.get('POSTGRES_USER', 'django'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'django'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}
print(f"DB CONFIG: {DATABASES}")


#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = "msgraphbackend.MSGraphBackend"
EMAIL_CHARSET = 'utf-8'


MSGRAPH_TENANT_ID = os.environ.get("MSGRAPH_TENANT_ID")
MSGRAPH_CLIENT_ID = os.environ.get("MSGRAPH_CLIENT_ID")
MSGRAPH_CLIENT_SECRET = os.environ.get("MSGRAPH_CLIENT_SECRET")

# The email address that has the mailbox
DEFAULT_FROM_EMAIL = 'noreply@browncountymtb.org'
# else:
    # Fallback to console for local dev
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

import ssl
EMAIL_SSL_CONTEXT = ssl._create_unverified_context()


PASSWORD_RESET_TIMEOUT = 3600

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'hourTracker.CustomUser'
AUTHENTICATION_BACKENDS = [
    'hourTracker.backends.CustomEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    ]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Indiana/Indianapolis'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # optional global static dir
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # used in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'




Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,       # Number of background processes
    'timeout': 90,      # Max seconds a task can run
    'retry': 120,       # When to retry a task if it fails
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',   # Uses your Django database as the broker
}

PHONENUMBER_DEFAULT_REGION = "US"