"""
Django settings for volunteer_tracker_app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import ssl
import environ
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#
env = environ.Env(DEBUG=(bool, False))
# Read .env file if it exists (local dev)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

#### SECURITY WARNING: keep the secret key used in production secret!
MODE = os.environ.get("MODE")

print(f"ENVS:")
print(f"MODE: {MODE}")

if MODE == "dev":
    DEBUG = True
else:
    DEBUG = False

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'fallback-secret')
print(f"SECRET_KEY: {SECRET_KEY}")

# 1. ALLOWED_HOSTS
if MODE == "dev":
    ALLOWED_HOSTS = ['*']
else:
    # Get the raw string from Railway env
    raw_hosts = os.environ.get("ALLOWED_HOSTS_LIST", "")
    
    # Start with your wildcard defaults
    ALLOWED_HOSTS = ['.browncountymtb.org', '.railway.app', 'localhost', '127.0.0.1']
    
    # Add the specific domains from your env var
    if raw_hosts:
        ALLOWED_HOSTS += [host.strip() for host in raw_hosts.split(",") if host]

# 2. CSRF_TRUSTED_ORIGINS
# This MUST have the full https:// prefix and NO wildcards
if MODE == "dev":
    CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]
else:
    raw_hosts = os.environ.get("ALLOWED_HOSTS_LIST")
    if raw_hosts:
        # Prepend https:// and ensure no leading dots (wildcards)
        CSRF_TRUSTED_ORIGINS = [
            f"https://{host.strip().lstrip('.')}" 
            for host in raw_hosts.split(",") 
            if host
        ]
    else:
        CSRF_TRUSTED_ORIGINS = ["https://mtbtest.casteel.pw"]

print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print(f"CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")

# Force the session cookie to be sent even when coming from an external link (like Gmail)
SESSION_COOKIE_SAMESITE = 'Lax' 

# If you are NOT using HTTPS (testing on a local IP like 10.0.10.140), 
# make sure these are False:
if MODE == "dev":
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_DOMAIN = None
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_AGE = 1209600

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 3  # 3 days in seconds (default)
# If this is set too low (like 3600), a 5-hour timezone jump 
# makes the link instantly expired.


print(f"SESSION_COOKIE_SECURE: {SESSION_COOKIE_SECURE}")
print(f"CSRF_COOKIE_SECURE: {CSRF_COOKIE_SECURE}")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'crispy_bulma',
    'django_q',
    # custom apps
    'accounts',
    'hourTracker',

]
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bulma",)
CRISPY_TEMPLATE_PACK = "bulma"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'volunteer_tracker_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hourTracker.context_processor.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'volunteer_tracker_app.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Set to DEBUG to see every SQL query
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'DEBUG', # This catches token/link failures
            'propagate': True,
        },
        # This will catch your custom prints/logs
        'hourTracker': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

DATABASES = {
    'default': dj_database_url.config(
        default=env('DATABASE_URL', default=f"sqlite:///{BASE_DIR}/db.sqlite3")
    )
}
print(f"DB CONFIG: {DATABASES}")


#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = "msgraphbackend.MSGraphBackend"
EMAIL_CHARSET = 'utf-8'

MSGRAPH_TENANT_ID = os.environ.get("MSGRAPH_TENANT_ID")
MSGRAPH_CLIENT_ID = os.environ.get("MSGRAPH_CLIENT_ID")
MSGRAPH_CLIENT_SECRET = os.environ.get("MSGRAPH_CLIENT_SECRET")
MSG_GRAPH_SDK_LOGGING = True  # This might help see the raw JSON in Railway logs

# The email address that has the mailbox
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", 'noreply@browncountymtb.org')
EMAIL_SSL_CONTEXT = ssl._create_unverified_context()

PASSWORD_PIN_TIMEOUT_MINUTES = 60  # PIN valid for 10 minutes

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'hourTracker.CustomUser'
AUTHENTICATION_BACKENDS = [
    'hourTracker.backends.CustomEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    ]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_TZ = True

if MODE == "dev":
    TIME_ZONE = 'America/Indiana/Indianapolis'
else:
    TIME_ZONE = 'UTC'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # optional global static dir
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # used in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'




Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,       # Number of background processes
    'timeout': 90,      # Max seconds a task can run
    'retry': 120,       # When to retry a task if it fails
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',   # Uses your Django database as the broker
}

PHONENUMBER_DEFAULT_REGION = "US"

