# Generated by Django 5.2.7 on 2025-11-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0003_category_alter_volunteerentry_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='VolunteerTask',
        ),
    ]
