# Generated by Django 6.0 on 2025-12-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0005_volunteerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerentry',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hourTracker.volunteerlocation'),
        ),
    ]
