# Generated by Django 6.0 on 2025-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0006_volunteerentry_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reward-images/')),
                ('hours_required', models.IntegerField(default=0)),
            ],
        ),
    ]
