# Generated by Django 5.2.9 on 2026-01-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0012_customuser_address_line_1_customuser_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='milestone_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
