# Generated by Django 5.2.9 on 2026-01-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0013_customuser_milestone_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='cody.casteel@browncountymtb.org', help_text='The email address that will receive milestone alerts.', max_length=254)),
                ('hour_requirement', models.IntegerField(default=8, help_text='The number of hours a volunteer needs to trigger the email.')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Uncheck this to globally disable milestone emails.')),
            ],
            options={
                'verbose_name': 'Global Reward Settings',
                'verbose_name_plural': 'Global Reward Settings',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='milestone_email_sent',
        ),
    ]
