# Generated by Django 5.2.9 on 2026-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0014_rewardsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='milestone_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
