# Generated by Django 5.2.9 on 2026-01-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourTracker', '0015_customuser_milestone_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='milestone_email_sent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_milestone_sent_year',
            field=models.IntegerField(default=0),
        ),
    ]
